/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import control.AdminMobiliario;
import modelo.Mobiliario;
import javax.swing.JOptionPane;

/**
 *
 * @author CARLOS MEDINA
 */
public class GestionMobiliario_Empleado extends javax.swing.JFrame {

    /**
     * Creates new form GestionMobiliario_Empleado
     */
    public GestionMobiliario_Empleado() {
        initComponents();
        this.setLocationRelativeTo(null);
         this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        registrar = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtIdentificacion_Registrar = new javax.swing.JTextField();
        txtValorUnitario_Registrar = new javax.swing.JTextField();
        btnAtras_Registrar = new javax.swing.JButton();
        btnGuardar_Registrar = new javax.swing.JButton();
        comboMobiliario = new javax.swing.JComboBox<>();
        jcomboEstado_Registrar = new javax.swing.JComboBox<>();
        jcomboDescripcion = new javax.swing.JComboBox<>();
        consultar = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        txtIdentificacion_Consultar = new javax.swing.JTextField();
        btnConsultar_Consultar = new javax.swing.JButton();
        btnAtras_Consultar = new javax.swing.JButton();
        btnEliminar_Consultar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla_gestionMobiliario = new javax.swing.JTable();
        modificar = new javax.swing.JPanel();
        txtIdentificacion_Modificar = new javax.swing.JTextField();
        btnConsultar_Modificar = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        txtDescripcion_Modificar = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtValorUnitario_Modificar = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        btnModificar_Modificar = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        btnAtras_Modificar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jcomboEstado_Modificar = new javax.swing.JComboBox<>();
        listar = new javax.swing.JPanel();
        btnListar = new javax.swing.JButton();
        btnAtras = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 2, 12)); // NOI18N
        jLabel2.setText("Nombre: ");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 2, 12)); // NOI18N
        jLabel3.setText("Identificacion: ");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 2, 12)); // NOI18N
        jLabel4.setText("Descripcion");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 2, 12)); // NOI18N
        jLabel5.setText("Estado");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 2, 12)); // NOI18N
        jLabel6.setText("Valor unitario:");

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Registrar.png"))); // NOI18N

        txtIdentificacion_Registrar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtIdentificacion_RegistrarKeyTyped(evt);
            }
        });

        txtValorUnitario_Registrar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtValorUnitario_RegistrarKeyTyped(evt);
            }
        });

        btnAtras_Registrar.setFont(new java.awt.Font("Times New Roman", 2, 12)); // NOI18N
        btnAtras_Registrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/regresar.png"))); // NOI18N
        btnAtras_Registrar.setText("Atras");
        btnAtras_Registrar.setBorder(null);
        btnAtras_Registrar.setBorderPainted(false);
        btnAtras_Registrar.setContentAreaFilled(false);
        btnAtras_Registrar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAtras_Registrar.setIconTextGap(-4);
        btnAtras_Registrar.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnAtras_Registrar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAtras_Registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtras_RegistrarActionPerformed(evt);
            }
        });

        btnGuardar_Registrar.setFont(new java.awt.Font("Times New Roman", 2, 12)); // NOI18N
        btnGuardar_Registrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/guardar.png"))); // NOI18N
        btnGuardar_Registrar.setText("Guardar");
        btnGuardar_Registrar.setBorder(null);
        btnGuardar_Registrar.setBorderPainted(false);
        btnGuardar_Registrar.setContentAreaFilled(false);
        btnGuardar_Registrar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnGuardar_Registrar.setIconTextGap(-4);
        btnGuardar_Registrar.setMaximumSize(new java.awt.Dimension(27, 35));
        btnGuardar_Registrar.setMinimumSize(new java.awt.Dimension(27, 35));
        btnGuardar_Registrar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnGuardar_Registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardar_RegistrarActionPerformed(evt);
            }
        });

        comboMobiliario.setFont(new java.awt.Font("Times New Roman", 2, 12)); // NOI18N
        comboMobiliario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione--", "Silla", "Mesa", "Cristaleria", "Mantel" }));
        comboMobiliario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboMobiliarioActionPerformed(evt);
            }
        });

        jcomboEstado_Registrar.setFont(new java.awt.Font("Times New Roman", 2, 12)); // NOI18N
        jcomboEstado_Registrar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione--", "Habilitado", "Deshabilitado" }));

        javax.swing.GroupLayout registrarLayout = new javax.swing.GroupLayout(registrar);
        registrar.setLayout(registrarLayout);
        registrarLayout.setHorizontalGroup(
            registrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registrarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(registrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(registrarLayout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addComponent(jLabel2)
                        .addGap(44, 44, 44)
                        .addComponent(comboMobiliario, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(registrarLayout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addGroup(registrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(registrarLayout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jLabel3))
                            .addGroup(registrarLayout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jLabel4))
                            .addGroup(registrarLayout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jLabel5))
                            .addComponent(jLabel6)
                            .addGroup(registrarLayout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addComponent(btnAtras_Registrar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(10, 10, 10)
                        .addGroup(registrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtIdentificacion_Registrar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtValorUnitario_Registrar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(registrarLayout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addComponent(btnGuardar_Registrar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jcomboDescripcion, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jcomboEstado_Registrar, 0, 118, Short.MAX_VALUE))))
                .addContainerGap(250, Short.MAX_VALUE))
        );
        registrarLayout.setVerticalGroup(
            registrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registrarLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(registrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(registrarLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel2))
                    .addComponent(comboMobiliario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(registrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(registrarLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel3)
                        .addGap(17, 17, 17)
                        .addComponent(jLabel4)
                        .addGap(17, 17, 17)
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)
                        .addGap(56, 56, 56)
                        .addComponent(btnAtras_Registrar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(registrarLayout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(txtIdentificacion_Registrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jcomboDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)
                        .addComponent(jcomboEstado_Registrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(txtValorUnitario_Registrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55)
                        .addComponent(btnGuardar_Registrar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("REGISTRAR", registrar);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 2, 12)); // NOI18N
        jLabel8.setText("Identificacion: ");

        txtIdentificacion_Consultar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtIdentificacion_ConsultarKeyTyped(evt);
            }
        });

        btnConsultar_Consultar.setFont(new java.awt.Font("Times New Roman", 2, 12)); // NOI18N
        btnConsultar_Consultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/buscar.png"))); // NOI18N
        btnConsultar_Consultar.setText("Consultar");
        btnConsultar_Consultar.setBorder(null);
        btnConsultar_Consultar.setBorderPainted(false);
        btnConsultar_Consultar.setContentAreaFilled(false);
        btnConsultar_Consultar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnConsultar_Consultar.setIconTextGap(-4);
        btnConsultar_Consultar.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnConsultar_Consultar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnConsultar_Consultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultar_ConsultarActionPerformed(evt);
            }
        });

        btnAtras_Consultar.setFont(new java.awt.Font("Times New Roman", 2, 12)); // NOI18N
        btnAtras_Consultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/regresar.png"))); // NOI18N
        btnAtras_Consultar.setText("Atras");
        btnAtras_Consultar.setBorder(null);
        btnAtras_Consultar.setBorderPainted(false);
        btnAtras_Consultar.setContentAreaFilled(false);
        btnAtras_Consultar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAtras_Consultar.setIconTextGap(-1);
        btnAtras_Consultar.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnAtras_Consultar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAtras_Consultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtras_ConsultarActionPerformed(evt);
            }
        });

        btnEliminar_Consultar.setFont(new java.awt.Font("Times New Roman", 2, 12)); // NOI18N
        btnEliminar_Consultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/eliminar.png"))); // NOI18N
        btnEliminar_Consultar.setText("Eliminar");
        btnEliminar_Consultar.setBorder(null);
        btnEliminar_Consultar.setBorderPainted(false);
        btnEliminar_Consultar.setContentAreaFilled(false);
        btnEliminar_Consultar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEliminar_Consultar.setIconTextGap(-1);
        btnEliminar_Consultar.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnEliminar_Consultar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnEliminar_Consultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminar_ConsultarActionPerformed(evt);
            }
        });

        tabla_gestionMobiliario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null}
            },
            new String [] {
                "Identificacion", "Nombre", "Descripcion", "Estado", "Valor Unitario"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabla_gestionMobiliario);

        javax.swing.GroupLayout consultarLayout = new javax.swing.GroupLayout(consultar);
        consultar.setLayout(consultarLayout);
        consultarLayout.setHorizontalGroup(
            consultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 590, Short.MAX_VALUE)
            .addGroup(consultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(consultarLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(consultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(consultarLayout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addComponent(jLabel8)
                            .addGap(39, 39, 39)
                            .addComponent(txtIdentificacion_Consultar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(20, 20, 20)
                            .addComponent(btnConsultar_Consultar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(consultarLayout.createSequentialGroup()
                            .addGap(200, 200, 200)
                            .addComponent(btnAtras_Consultar)
                            .addGap(183, 183, 183)
                            .addComponent(btnEliminar_Consultar)))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        consultarLayout.setVerticalGroup(
            consultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 280, Short.MAX_VALUE)
            .addGroup(consultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(consultarLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(consultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnConsultar_Consultar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(consultarLayout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addGroup(consultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel8)
                                .addComponent(txtIdentificacion_Consultar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGap(40, 40, 40)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(60, 60, 60)
                    .addGroup(consultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(consultarLayout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addComponent(btnAtras_Consultar))
                        .addComponent(btnEliminar_Consultar))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("CONSULTAR", consultar);

        txtIdentificacion_Modificar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtIdentificacion_ModificarKeyTyped(evt);
            }
        });

        btnConsultar_Modificar.setFont(new java.awt.Font("Times New Roman", 2, 12)); // NOI18N
        btnConsultar_Modificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/buscar.png"))); // NOI18N
        btnConsultar_Modificar.setText("Consultar");
        btnConsultar_Modificar.setBorder(null);
        btnConsultar_Modificar.setBorderPainted(false);
        btnConsultar_Modificar.setContentAreaFilled(false);
        btnConsultar_Modificar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnConsultar_Modificar.setIconTextGap(-1);
        btnConsultar_Modificar.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnConsultar_Modificar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnConsultar_Modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultar_ModificarActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Times New Roman", 2, 12)); // NOI18N
        jLabel10.setText("Descripcion");

        txtDescripcion_Modificar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDescripcion_ModificarKeyTyped(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Times New Roman", 2, 12)); // NOI18N
        jLabel11.setText("Valor unitario");

        txtValorUnitario_Modificar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtValorUnitario_ModificarKeyTyped(evt);
            }
        });

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Registrar.png"))); // NOI18N

        btnModificar_Modificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/editar.png"))); // NOI18N
        btnModificar_Modificar.setBorder(null);
        btnModificar_Modificar.setBorderPainted(false);
        btnModificar_Modificar.setContentAreaFilled(false);
        btnModificar_Modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificar_ModificarActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Times New Roman", 2, 12)); // NOI18N
        jLabel9.setText("Identificacion");

        btnAtras_Modificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/regresar.png"))); // NOI18N
        btnAtras_Modificar.setText("Atras");
        btnAtras_Modificar.setBorder(null);
        btnAtras_Modificar.setBorderPainted(false);
        btnAtras_Modificar.setContentAreaFilled(false);
        btnAtras_Modificar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAtras_Modificar.setIconTextGap(-1);
        btnAtras_Modificar.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnAtras_Modificar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAtras_Modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtras_ModificarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 2, 12)); // NOI18N
        jLabel1.setText("Estado");

        jcomboEstado_Modificar.setFont(new java.awt.Font("Times New Roman", 2, 12)); // NOI18N
        jcomboEstado_Modificar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione--", "Habilitado", "Deshabilitado" }));

        javax.swing.GroupLayout modificarLayout = new javax.swing.GroupLayout(modificar);
        modificar.setLayout(modificarLayout);
        modificarLayout.setHorizontalGroup(
            modificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(modificarLayout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addComponent(jLabel9)
                .addGap(29, 29, 29)
                .addComponent(txtIdentificacion_Modificar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(299, Short.MAX_VALUE))
            .addGroup(modificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(modificarLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(modificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(modificarLayout.createSequentialGroup()
                            .addGap(240, 240, 240)
                            .addComponent(btnConsultar_Modificar))
                        .addGroup(modificarLayout.createSequentialGroup()
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(35, 35, 35)
                            .addGroup(modificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel10)
                                .addComponent(jLabel11)
                                .addGroup(modificarLayout.createSequentialGroup()
                                    .addGap(5, 5, 5)
                                    .addComponent(jLabel1))
                                .addGroup(modificarLayout.createSequentialGroup()
                                    .addGap(55, 55, 55)
                                    .addComponent(btnAtras_Modificar)))
                            .addGap(17, 17, 17)
                            .addGroup(modificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtDescripcion_Modificar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtValorUnitario_Modificar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(modificarLayout.createSequentialGroup()
                                    .addGap(6, 6, 6)
                                    .addComponent(jcomboEstado_Modificar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(btnModificar_Modificar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        modificarLayout.setVerticalGroup(
            modificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(modificarLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(modificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIdentificacion_Modificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addContainerGap(227, Short.MAX_VALUE))
            .addGroup(modificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(modificarLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(btnConsultar_Modificar)
                    .addGap(27, 27, 27)
                    .addGroup(modificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(modificarLayout.createSequentialGroup()
                            .addGap(4, 4, 4)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(modificarLayout.createSequentialGroup()
                            .addGap(3, 3, 3)
                            .addComponent(jLabel10)
                            .addGap(24, 24, 24)
                            .addComponent(jLabel11)
                            .addGap(29, 29, 29)
                            .addComponent(jLabel1)
                            .addGap(36, 36, 36)
                            .addComponent(btnAtras_Modificar))
                        .addGroup(modificarLayout.createSequentialGroup()
                            .addComponent(txtDescripcion_Modificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(txtValorUnitario_Modificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(26, 26, 26)
                            .addComponent(jcomboEstado_Modificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(modificarLayout.createSequentialGroup()
                            .addGap(134, 134, 134)
                            .addComponent(btnModificar_Modificar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("MODIFICAR", modificar);

        btnListar.setFont(new java.awt.Font("Times New Roman", 2, 12)); // NOI18N
        btnListar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/listar.png"))); // NOI18N
        btnListar.setText("Listar");
        btnListar.setBorder(null);
        btnListar.setBorderPainted(false);
        btnListar.setContentAreaFilled(false);
        btnListar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnListar.setIconTextGap(-1);
        btnListar.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnListar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarActionPerformed(evt);
            }
        });

        btnAtras.setFont(new java.awt.Font("Times New Roman", 2, 12)); // NOI18N
        btnAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/regresar.png"))); // NOI18N
        btnAtras.setText("Atras");
        btnAtras.setBorder(null);
        btnAtras.setBorderPainted(false);
        btnAtras.setContentAreaFilled(false);
        btnAtras.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAtras.setIconTextGap(-4);
        btnAtras.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnAtras.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        jLabel12.setText("LISTADO MOBILIARIO");

        table_ListadoMobilirio.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Identificacion", "Nombre", "Descripcion", "Estado", "Valor Unitario"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(table_ListadoMobilirio);

        javax.swing.GroupLayout listarLayout = new javax.swing.GroupLayout(listar);
        listar.setLayout(listarLayout);
        listarLayout.setHorizontalGroup(
            listarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, listarLayout.createSequentialGroup()
                .addGap(117, 117, 117)
                .addComponent(btnAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnListar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(186, 186, 186))
            .addGroup(listarLayout.createSequentialGroup()
                .addGroup(listarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(listarLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(listarLayout.createSequentialGroup()
                        .addGap(173, 173, 173)
                        .addComponent(jLabel12)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        listarLayout.setVerticalGroup(
            listarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, listarLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(listarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnListar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31))
        );

        jTabbedPane1.addTab("LISTAR", listar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtIdentificacion_RegistrarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIdentificacion_RegistrarKeyTyped
        char c = evt.getKeyChar();
        if(c<'0' || c>'9') evt.consume();
    }//GEN-LAST:event_txtIdentificacion_RegistrarKeyTyped

    private void txtValorUnitario_RegistrarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtValorUnitario_RegistrarKeyTyped
        char c = evt.getKeyChar();
        if(c<'0' || c>'9') evt.consume();
    }//GEN-LAST:event_txtValorUnitario_RegistrarKeyTyped

    private void btnAtras_RegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtras_RegistrarActionPerformed
        
    }//GEN-LAST:event_btnAtras_RegistrarActionPerformed

    private void btnGuardar_RegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardar_RegistrarActionPerformed
         try {
            if (comboMobiliario.getSelectedItem().equals("Seleccione")
                || txtIdentificacion_Registrar.getText().equals("")
                || txtValorUnitario_Registrar.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Hay campos vacios");
            }

            if (!txtIdentificacion_Registrar.getText().equals("")
                && !txtValorUnitario_Registrar.getText().equals("")
                || jcomboEstado_Registrar.getSelectedItem().equals("Habilitado")) {
                Mobiliario registrar = new Mobiliario();
                registrar.Nombre = comboMobiliario.getSelectedItem().toString();
                registrar.Num_Identificacion = txtIdentificacion_Registrar.getText();
                registrar.Estado = jcomboEstado_Registrar.getSelectedItem().toString();
                registrar.valorUnitario = txtValorUnitario_Registrar.getText();
               
                AdminMobiliario.registrar(registrar);
                JOptionPane.showMessageDialog(null, "Se ha registrado el mobiliario :  " + comboMobiliario.getSelectedItem());

                comboMobiliario.setSelectedIndex(0);
                txtIdentificacion_Registrar.setText(null);
                txtValorUnitario_Registrar.setText(null);
                jcomboEstado_Registrar.setSelectedIndex(0);

            }
            if (!txtIdentificacion_Registrar.getText().equals("")
                && !txtValorUnitario_Registrar.getText().equals("")
                || jcomboEstado_Registrar.getSelectedItem().equals("Deshabilitado")) {
                Mobiliario registrar = new Mobiliario();
                registrar.Nombre = comboMobiliario.getSelectedItem().toString();
                registrar.Num_Identificacion = txtIdentificacion_Registrar.getText();
                registrar.Estado = jcomboEstado_Registrar.getSelectedItem().toString();
                registrar.valorUnitario = txtValorUnitario_Registrar.getText();
               
                 AdminMobiliario.registrar(registrar);
                
                JOptionPane.showMessageDialog(null, "Se ha registrado el mobiliario :  " + comboMobiliario.getSelectedItem());

                comboMobiliario.setSelectedIndex(0);
                txtIdentificacion_Registrar.setText(null);
                txtValorUnitario_Registrar.setText(null);
                jcomboEstado_Registrar.setSelectedIndex(0);

            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Se ha producido un error :  " + e);
        }
    }//GEN-LAST:event_btnGuardar_RegistrarActionPerformed

    private void txtIdentificacion_ConsultarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIdentificacion_ConsultarKeyTyped
        char c = evt.getKeyChar();
        if(c<'0' || c>'9') evt.consume();
    }//GEN-LAST:event_txtIdentificacion_ConsultarKeyTyped

    private void btnConsultar_ConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultar_ConsultarActionPerformed
        
    }//GEN-LAST:event_btnConsultar_ConsultarActionPerformed

    private void btnAtras_ConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtras_ConsultarActionPerformed
       
    }//GEN-LAST:event_btnAtras_ConsultarActionPerformed

    private void btnEliminar_ConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminar_ConsultarActionPerformed
        
    }//GEN-LAST:event_btnEliminar_ConsultarActionPerformed

    private void txtIdentificacion_ModificarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIdentificacion_ModificarKeyTyped
        char c = evt.getKeyChar();
        if(c<'0' || c>'9') evt.consume();
    }//GEN-LAST:event_txtIdentificacion_ModificarKeyTyped

    private void btnConsultar_ModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultar_ModificarActionPerformed
        

    }//GEN-LAST:event_btnConsultar_ModificarActionPerformed

    private void txtDescripcion_ModificarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDescripcion_ModificarKeyTyped
        char c = evt.getKeyChar();
        if((c<'a' || c>'z') && (c<'A')|(c>'Z')) evt.consume();
    }//GEN-LAST:event_txtDescripcion_ModificarKeyTyped

    private void txtValorUnitario_ModificarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtValorUnitario_ModificarKeyTyped
        char c = evt.getKeyChar();
        if(c<'0' || c>'9') evt.consume();
    }//GEN-LAST:event_txtValorUnitario_ModificarKeyTyped

    private void btnModificar_ModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificar_ModificarActionPerformed
       
    }//GEN-LAST:event_btnModificar_ModificarActionPerformed

    private void btnAtras_ModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtras_ModificarActionPerformed
        
    }//GEN-LAST:event_btnAtras_ModificarActionPerformed

    private void btnListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarActionPerformed
       
    }//GEN-LAST:event_btnListarActionPerformed

    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
       
    }//GEN-LAST:event_btnAtrasActionPerformed

    private void comboMobiliarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboMobiliarioActionPerformed
       if (comboMobiliario.getSelectedItem().equals("Seleccione--")) {
            jcomboDescripcion.removeAllItems();
        }
        if (comboMobiliario.getSelectedItem().equals("Silla")) {
            jcomboDescripcion.removeAllItems();
            jcomboDescripcion.addItem("Plastica");
            jcomboDescripcion.addItem("Madera");
            jcomboDescripcion.addItem("Metalica");
        }
        if (comboMobiliario.getSelectedItem().equals("Mesa")) {
            jcomboDescripcion.removeAllItems();
            jcomboDescripcion.addItem("Redonda");
            jcomboDescripcion.addItem("Cuadrada");
        }
        if (comboMobiliario.getSelectedItem().equals("Cristaleria")) {
            jcomboDescripcion.removeAllItems();
            jcomboDescripcion.addItem("Copa");
            jcomboDescripcion.addItem("Vajillas");
        }
        if (comboMobiliario.getSelectedItem().equals("Mantel")) {
            jcomboDescripcion.removeAllItems();
            jcomboDescripcion.addItem("Decorado");
            jcomboDescripcion.addItem("Liso");
        }
    }//GEN-LAST:event_comboMobiliarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionMobiliario_Empleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionMobiliario_Empleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionMobiliario_Empleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionMobiliario_Empleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GestionMobiliario_Empleado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnAtras_Consultar;
    private javax.swing.JButton btnAtras_Modificar;
    private javax.swing.JButton btnAtras_Registrar;
    private javax.swing.JButton btnConsultar_Consultar;
    private javax.swing.JButton btnConsultar_Modificar;
    private javax.swing.JButton btnEliminar_Consultar;
    private javax.swing.JButton btnGuardar_Registrar;
    private javax.swing.JButton btnListar;
    private javax.swing.JButton btnModificar_Modificar;
    private javax.swing.JComboBox<String> comboMobiliario;
    private javax.swing.JPanel consultar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JComboBox<String> jcomboDescripcion;
    private javax.swing.JComboBox<String> jcomboEstado_Modificar;
    private javax.swing.JComboBox<String> jcomboEstado_Registrar;
    private javax.swing.JPanel listar;
    private javax.swing.JPanel modificar;
    private javax.swing.JPanel registrar;
    private javax.swing.JTable tabla_gestionMobiliario;
    public final javax.swing.JTable table_ListadoMobilirio = new javax.swing.JTable();
    private javax.swing.JTextField txtDescripcion_Modificar;
    private javax.swing.JTextField txtIdentificacion_Consultar;
    private javax.swing.JTextField txtIdentificacion_Modificar;
    private javax.swing.JTextField txtIdentificacion_Registrar;
    private javax.swing.JTextField txtValorUnitario_Modificar;
    private javax.swing.JTextField txtValorUnitario_Registrar;
    // End of variables declaration//GEN-END:variables
}
