/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import control.AdminMobiliario;
import modelo.Mobiliario;
import javax.swing.JOptionPane;

/**
 *
 * @author CARLOS MEDINA
 */
public class GestionMobiliario extends javax.swing.JFrame {

    /**
     * Creates new form GestionMobiliario
     */
    public GestionMobiliario() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
    }

    private void registrar() {
        try {
            if (comboMobiliario.getSelectedItem().equals("Seleccione")
                    || txtIdentificacion_Registrar.getText().equals("")
                    || txtValorUnitario_Registrar.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Hay campos vacios");
            }

            if (!txtIdentificacion_Registrar.getText().equals("")
                    && !txtValorUnitario_Registrar.getText().equals("")
                    || jcomboEstado_Registrar.getSelectedItem().equals("Habilitado")) {
                Mobiliario registrar = new Mobiliario();
                registrar.Nombre = comboMobiliario.getSelectedItem().toString();
                registrar.Num_Identificacion = txtIdentificacion_Registrar.getText();
                registrar.Estado = jcomboEstado_Registrar.getSelectedItem().toString();
                registrar.valorUnitario = txtValorUnitario_Registrar.getText();

                AdminMobiliario.registrar(registrar);
                JOptionPane.showMessageDialog(null, "Se ha registrado el mobiliario :  " + comboMobiliario.getSelectedItem());

                comboMobiliario.setSelectedIndex(0);
                txtIdentificacion_Registrar.setText(null);
                txtValorUnitario_Registrar.setText(null);
                jcomboEstado_Registrar.setSelectedIndex(0);

            }
            if (!txtIdentificacion_Registrar.getText().equals("")
                    && !txtValorUnitario_Registrar.getText().equals("")
                    || jcomboEstado_Registrar.getSelectedItem().equals("Deshabilitado")) {
                Mobiliario registrar = new Mobiliario();
                registrar.Nombre = comboMobiliario.getSelectedItem().toString();
                registrar.Num_Identificacion = txtIdentificacion_Registrar.getText();
                registrar.Estado = jcomboEstado_Registrar.getSelectedItem().toString();
                registrar.valorUnitario = txtValorUnitario_Registrar.getText();

                AdminMobiliario.registrar(registrar);

                JOptionPane.showMessageDialog(null, "Se ha registrado el mobiliario :  " + comboMobiliario.getSelectedItem());

                comboMobiliario.setSelectedIndex(0);
                txtIdentificacion_Registrar.setText(null);
                txtValorUnitario_Registrar.setText(null);
                jcomboEstado_Registrar.setSelectedIndex(0);

            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Se ha producido un error :  " + e);
        }
    }

    private void mostrarComboMobiliario() {
        if (comboMobiliario.getSelectedItem().equals("Seleccione--")) {
            jcomboDescripcion.removeAllItems();
        }
        if (comboMobiliario.getSelectedItem().equals("Silla")) {
            jcomboDescripcion.removeAllItems();
            jcomboDescripcion.addItem("Plastica");
            jcomboDescripcion.addItem("Madera");
            jcomboDescripcion.addItem("Metalica");
        }
        if (comboMobiliario.getSelectedItem().equals("Mesa")) {
            jcomboDescripcion.removeAllItems();
            jcomboDescripcion.addItem("Redonda");
            jcomboDescripcion.addItem("Cuadrada");
        }
        if (comboMobiliario.getSelectedItem().equals("Cristaleria")) {
            jcomboDescripcion.removeAllItems();
            jcomboDescripcion.addItem("Copa");
            jcomboDescripcion.addItem("Vajillas");
        }
        if (comboMobiliario.getSelectedItem().equals("Mantel")) {
            jcomboDescripcion.removeAllItems();
            jcomboDescripcion.addItem("Decorado");
            jcomboDescripcion.addItem("Liso");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        registrar = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtIdentificacion_Registrar = new javax.swing.JTextField();
        btnAtras_Registra = new javax.swing.JButton();
        bntGuardar_Registrar = new javax.swing.JButton();
        comboMobiliario = new javax.swing.JComboBox<>();
        jcomboEstado_Registrar = new javax.swing.JComboBox<>();
        jcomboDescripcion = new javax.swing.JComboBox<>();
        consultar = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        txtIdentificacion_Consultar = new javax.swing.JTextField();
        btnConsultar_Consultar = new javax.swing.JButton();
        btnAtras_consultar = new javax.swing.JButton();
        btnEliminar_Consultar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla_gestionMobilirio = new javax.swing.JTable();
        modificar = new javax.swing.JPanel();
        txtIdentificacion_Modificar = new javax.swing.JTextField();
        btnConsultar_Modificar = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        txtDescripcion_Modificar = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtValorUnitario_Modificar = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        btnModificar_Modificar = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        btnAtras_Modificar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jcomboEstado_Modificar = new javax.swing.JComboBox<>();
        listar = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        btnListar_Consultar1 = new javax.swing.JButton();
        btnAtras = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Times New Roman", 2, 12)); // NOI18N
        jLabel2.setText("Nombre: ");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 2, 12)); // NOI18N
        jLabel3.setText("Identificacion: ");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 2, 12)); // NOI18N
        jLabel4.setText("Descripcion");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 2, 12)); // NOI18N
        jLabel5.setText("Estado");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 2, 12)); // NOI18N
        jLabel6.setText("Valor unitario:");

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Registrar.png"))); // NOI18N

        txtIdentificacion_Registrar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtIdentificacion_RegistrarKeyTyped(evt);
            }
        });

        txtValorUnitario_Registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtValorUnitario_RegistrarActionPerformed(evt);
            }
        });
        txtValorUnitario_Registrar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtValorUnitario_RegistrarKeyTyped(evt);
            }
        });

        btnAtras_Registra.setFont(new java.awt.Font("Times New Roman", 2, 12)); // NOI18N
        btnAtras_Registra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/regresar.png"))); // NOI18N
        btnAtras_Registra.setText("Atras");
        btnAtras_Registra.setBorder(null);
        btnAtras_Registra.setBorderPainted(false);
        btnAtras_Registra.setContentAreaFilled(false);
        btnAtras_Registra.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAtras_Registra.setIconTextGap(-4);
        btnAtras_Registra.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnAtras_Registra.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAtras_Registra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtras_RegistraActionPerformed(evt);
            }
        });

        bntGuardar_Registrar.setFont(new java.awt.Font("Times New Roman", 2, 12)); // NOI18N
        bntGuardar_Registrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/guardar.png"))); // NOI18N
        bntGuardar_Registrar.setText("Guardar");
        bntGuardar_Registrar.setBorder(null);
        bntGuardar_Registrar.setBorderPainted(false);
        bntGuardar_Registrar.setContentAreaFilled(false);
        bntGuardar_Registrar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bntGuardar_Registrar.setIconTextGap(-4);
        bntGuardar_Registrar.setMaximumSize(new java.awt.Dimension(27, 35));
        bntGuardar_Registrar.setMinimumSize(new java.awt.Dimension(27, 35));
        bntGuardar_Registrar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bntGuardar_Registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntGuardar_RegistrarActionPerformed(evt);
            }
        });

        comboMobiliario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione--", "Silla", "Mesa", "Cristaleria", "Mantel" }));
        comboMobiliario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboMobiliarioActionPerformed(evt);
            }
        });

        jcomboEstado_Registrar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione--", "Habiltado", "Deshabilitado" }));

        jcomboDescripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcomboDescripcionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout registrarLayout = new javax.swing.GroupLayout(registrar);
        registrar.setLayout(registrarLayout);
        registrarLayout.setHorizontalGroup(
            registrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registrarLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(registrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(registrarLayout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addComponent(jLabel2)
                        .addGap(44, 44, 44)
                        .addComponent(comboMobiliario, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(registrarLayout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addGroup(registrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(registrarLayout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jLabel3))
                            .addGroup(registrarLayout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jLabel4))
                            .addGroup(registrarLayout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jLabel5))
                            .addComponent(jLabel6)
                            .addGroup(registrarLayout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addComponent(btnAtras_Registra, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(10, 10, 10)
                        .addGroup(registrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtIdentificacion_Registrar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jcomboDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jcomboEstado_Registrar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtValorUnitario_Registrar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(registrarLayout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addComponent(bntGuardar_Registrar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(257, Short.MAX_VALUE))
        );
        registrarLayout.setVerticalGroup(
            registrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registrarLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(registrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(registrarLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel2))
                    .addComponent(comboMobiliario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(registrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(registrarLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel3)
                        .addGap(17, 17, 17)
                        .addComponent(jLabel4)
                        .addGap(17, 17, 17)
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)
                        .addGap(56, 56, 56)
                        .addComponent(btnAtras_Registra, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(registrarLayout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(txtIdentificacion_Registrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jcomboDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jcomboEstado_Registrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(txtValorUnitario_Registrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55)
                        .addComponent(bntGuardar_Registrar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(59, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("REGISTRAR", registrar);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 2, 12)); // NOI18N
        jLabel8.setText("Identificacion: ");

        txtIdentificacion_Consultar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtIdentificacion_ConsultarKeyTyped(evt);
            }
        });

        btnConsultar_Consultar.setFont(new java.awt.Font("Times New Roman", 2, 12)); // NOI18N
        btnConsultar_Consultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/buscar.png"))); // NOI18N
        btnConsultar_Consultar.setText("Consultar");
        btnConsultar_Consultar.setBorder(null);
        btnConsultar_Consultar.setBorderPainted(false);
        btnConsultar_Consultar.setContentAreaFilled(false);
        btnConsultar_Consultar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnConsultar_Consultar.setIconTextGap(-4);
        btnConsultar_Consultar.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnConsultar_Consultar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnConsultar_Consultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultar_ConsultarActionPerformed(evt);
            }
        });

        btnAtras_consultar.setFont(new java.awt.Font("Times New Roman", 2, 12)); // NOI18N
        btnAtras_consultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/regresar.png"))); // NOI18N
        btnAtras_consultar.setText("Atras");
        btnAtras_consultar.setBorder(null);
        btnAtras_consultar.setBorderPainted(false);
        btnAtras_consultar.setContentAreaFilled(false);
        btnAtras_consultar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAtras_consultar.setIconTextGap(-1);
        btnAtras_consultar.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnAtras_consultar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAtras_consultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtras_consultarActionPerformed(evt);
            }
        });

        btnEliminar_Consultar.setFont(new java.awt.Font("Times New Roman", 2, 12)); // NOI18N
        btnEliminar_Consultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/eliminar.png"))); // NOI18N
        btnEliminar_Consultar.setText("Eliminar");
        btnEliminar_Consultar.setBorder(null);
        btnEliminar_Consultar.setBorderPainted(false);
        btnEliminar_Consultar.setContentAreaFilled(false);
        btnEliminar_Consultar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEliminar_Consultar.setIconTextGap(-1);
        btnEliminar_Consultar.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnEliminar_Consultar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnEliminar_Consultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminar_ConsultarActionPerformed(evt);
            }
        });

        tabla_gestionMobilirio.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null}
            },
            new String [] {
                "Identificacion", "Nombre", "Descripcion", "Estado", "Valor Unitario"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabla_gestionMobilirio);

        javax.swing.GroupLayout consultarLayout = new javax.swing.GroupLayout(consultar);
        consultar.setLayout(consultarLayout);
        consultarLayout.setHorizontalGroup(
            consultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, consultarLayout.createSequentialGroup()
                .addContainerGap(393, Short.MAX_VALUE)
                .addComponent(btnEliminar_Consultar)
                .addGap(183, 183, 183))
            .addGroup(consultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(consultarLayout.createSequentialGroup()
                    .addGap(0, 34, Short.MAX_VALUE)
                    .addGroup(consultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(consultarLayout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addComponent(jLabel8)
                            .addGap(39, 39, 39)
                            .addComponent(txtIdentificacion_Consultar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(20, 20, 20)
                            .addComponent(btnConsultar_Consultar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(consultarLayout.createSequentialGroup()
                            .addGap(200, 200, 200)
                            .addComponent(btnAtras_consultar)))
                    .addGap(0, 35, Short.MAX_VALUE)))
        );
        consultarLayout.setVerticalGroup(
            consultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, consultarLayout.createSequentialGroup()
                .addContainerGap(250, Short.MAX_VALUE)
                .addComponent(btnEliminar_Consultar)
                .addGap(49, 49, 49))
            .addGroup(consultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(consultarLayout.createSequentialGroup()
                    .addGap(0, 44, Short.MAX_VALUE)
                    .addGroup(consultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnConsultar_Consultar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(consultarLayout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addGroup(consultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel8)
                                .addComponent(txtIdentificacion_Consultar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGap(40, 40, 40)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(70, 70, 70)
                    .addComponent(btnAtras_consultar)
                    .addGap(0, 45, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("CONSULTAR", consultar);

        txtIdentificacion_Modificar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtIdentificacion_ModificarKeyTyped(evt);
            }
        });

        btnConsultar_Modificar.setFont(new java.awt.Font("Times New Roman", 2, 12)); // NOI18N
        btnConsultar_Modificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/buscar.png"))); // NOI18N
        btnConsultar_Modificar.setText("Consultar");
        btnConsultar_Modificar.setBorder(null);
        btnConsultar_Modificar.setBorderPainted(false);
        btnConsultar_Modificar.setContentAreaFilled(false);
        btnConsultar_Modificar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnConsultar_Modificar.setIconTextGap(-1);
        btnConsultar_Modificar.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnConsultar_Modificar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnConsultar_Modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultar_ModificarActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Times New Roman", 2, 12)); // NOI18N
        jLabel10.setText("Descripcion");

        txtDescripcion_Modificar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDescripcion_ModificarKeyTyped(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Times New Roman", 2, 12)); // NOI18N
        jLabel11.setText("Valor unitario");

        txtValorUnitario_Modificar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtValorUnitario_ModificarKeyTyped(evt);
            }
        });

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Registrar.png"))); // NOI18N

        btnModificar_Modificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/editar.png"))); // NOI18N
        btnModificar_Modificar.setBorder(null);
        btnModificar_Modificar.setBorderPainted(false);
        btnModificar_Modificar.setContentAreaFilled(false);
        btnModificar_Modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificar_ModificarActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Times New Roman", 2, 12)); // NOI18N
        jLabel9.setText("Identificacion");

        btnAtras_Modificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/regresar.png"))); // NOI18N
        btnAtras_Modificar.setText("Atras");
        btnAtras_Modificar.setBorder(null);
        btnAtras_Modificar.setBorderPainted(false);
        btnAtras_Modificar.setContentAreaFilled(false);
        btnAtras_Modificar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAtras_Modificar.setIconTextGap(-1);
        btnAtras_Modificar.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnAtras_Modificar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAtras_Modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtras_ModificarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 2, 12)); // NOI18N
        jLabel1.setText("Estado");

        jcomboEstado_Modificar.setFont(new java.awt.Font("Times New Roman", 2, 12)); // NOI18N
        jcomboEstado_Modificar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione--", "Habilitado", "Deshabilitado" }));

        javax.swing.GroupLayout modificarLayout = new javax.swing.GroupLayout(modificar);
        modificar.setLayout(modificarLayout);
        modificarLayout.setHorizontalGroup(
            modificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(modificarLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(modificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(modificarLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel9)
                        .addGap(26, 26, 26)
                        .addComponent(txtIdentificacion_Modificar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(btnConsultar_Modificar))
                    .addGroup(modificarLayout.createSequentialGroup()
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addGroup(modificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addGroup(modificarLayout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(jLabel1))
                            .addGroup(modificarLayout.createSequentialGroup()
                                .addGap(55, 55, 55)
                                .addComponent(btnAtras_Modificar)))
                        .addGap(17, 17, 17)
                        .addGroup(modificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDescripcion_Modificar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtValorUnitario_Modificar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(modificarLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jcomboEstado_Modificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(6, 6, 6)
                        .addComponent(btnModificar_Modificar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(184, Short.MAX_VALUE))
        );
        modificarLayout.setVerticalGroup(
            modificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(modificarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(modificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnConsultar_Modificar)
                    .addGroup(modificarLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(modificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(txtIdentificacion_Modificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(16, 16, 16)
                .addGroup(modificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(modificarLayout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(modificarLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel10)
                        .addGap(24, 24, 24)
                        .addComponent(jLabel11)
                        .addGap(29, 29, 29)
                        .addComponent(jLabel1)
                        .addGap(56, 56, 56)
                        .addComponent(btnAtras_Modificar))
                    .addGroup(modificarLayout.createSequentialGroup()
                        .addComponent(txtDescripcion_Modificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtValorUnitario_Modificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jcomboEstado_Modificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(modificarLayout.createSequentialGroup()
                        .addGap(154, 154, 154)
                        .addComponent(btnModificar_Modificar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(67, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("MODIFICAR", modificar);

        table_ListadoMobilirio.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Identificacion", "Nombre", "Descripcion", "Estado", "Valor Unitario"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(table_ListadoMobilirio);

        btnListar_Consultar1.setFont(new java.awt.Font("Times New Roman", 2, 12)); // NOI18N
        btnListar_Consultar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/listar.png"))); // NOI18N
        btnListar_Consultar1.setText("Listar");
        btnListar_Consultar1.setBorder(null);
        btnListar_Consultar1.setBorderPainted(false);
        btnListar_Consultar1.setContentAreaFilled(false);
        btnListar_Consultar1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnListar_Consultar1.setIconTextGap(-1);
        btnListar_Consultar1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnListar_Consultar1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnListar_Consultar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListar_Consultar1ActionPerformed(evt);
            }
        });

        btnAtras.setFont(new java.awt.Font("Times New Roman", 2, 12)); // NOI18N
        btnAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/regresar.png"))); // NOI18N
        btnAtras.setText("Atras");
        btnAtras.setBorder(null);
        btnAtras.setBorderPainted(false);
        btnAtras.setContentAreaFilled(false);
        btnAtras.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAtras.setIconTextGap(-4);
        btnAtras.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnAtras.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        jLabel12.setText("LISTADO MOBILIARIO");

        javax.swing.GroupLayout listarLayout = new javax.swing.GroupLayout(listar);
        listar.setLayout(listarLayout);
        listarLayout.setHorizontalGroup(
            listarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(listarLayout.createSequentialGroup()
                .addGap(129, 129, 129)
                .addComponent(btnAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnListar_Consultar1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(176, 176, 176))
            .addGroup(listarLayout.createSequentialGroup()
                .addGap(206, 206, 206)
                .addComponent(jLabel12)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, listarLayout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );
        listarLayout.setVerticalGroup(
            listarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, listarLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(listarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnListar_Consultar1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAtras, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(75, 75, 75))
        );

        jTabbedPane1.addTab("LISTAR", listar);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtIdentificacion_RegistrarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIdentificacion_RegistrarKeyTyped
        char c = evt.getKeyChar();
        if (c < '0' || c > '9') {
            evt.consume();
        }
    }//GEN-LAST:event_txtIdentificacion_RegistrarKeyTyped

    private void txtValorUnitario_RegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtValorUnitario_RegistrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtValorUnitario_RegistrarActionPerformed

    private void txtValorUnitario_RegistrarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtValorUnitario_RegistrarKeyTyped
        char c = evt.getKeyChar();
        if (c < '0' || c > '9') {
            evt.consume();
        }
    }//GEN-LAST:event_txtValorUnitario_RegistrarKeyTyped

    private void btnAtras_RegistraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtras_RegistraActionPerformed

    }//GEN-LAST:event_btnAtras_RegistraActionPerformed

    private void bntGuardar_RegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntGuardar_RegistrarActionPerformed
        registrar();
    }//GEN-LAST:event_bntGuardar_RegistrarActionPerformed

    private void comboMobiliarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboMobiliarioActionPerformed
        mostrarComboMobiliario();
    }//GEN-LAST:event_comboMobiliarioActionPerformed

    private void jcomboDescripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcomboDescripcionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcomboDescripcionActionPerformed

    private void txtIdentificacion_ConsultarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIdentificacion_ConsultarKeyTyped
        char c = evt.getKeyChar();
        if (c < '0' || c > '9') {
            evt.consume();
        }
    }//GEN-LAST:event_txtIdentificacion_ConsultarKeyTyped

    private void btnConsultar_ConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultar_ConsultarActionPerformed

    }//GEN-LAST:event_btnConsultar_ConsultarActionPerformed

    private void btnAtras_consultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtras_consultarActionPerformed

    }//GEN-LAST:event_btnAtras_consultarActionPerformed

    private void btnEliminar_ConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminar_ConsultarActionPerformed

    }//GEN-LAST:event_btnEliminar_ConsultarActionPerformed

    private void txtIdentificacion_ModificarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIdentificacion_ModificarKeyTyped
        char c = evt.getKeyChar();
        if (c < '0' || c > '9') {
            evt.consume();
        }
    }//GEN-LAST:event_txtIdentificacion_ModificarKeyTyped

    private void btnConsultar_ModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultar_ModificarActionPerformed

    }//GEN-LAST:event_btnConsultar_ModificarActionPerformed

    private void txtDescripcion_ModificarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDescripcion_ModificarKeyTyped
        char c = evt.getKeyChar();
        if ((c < 'a' || c > 'z') && (c < 'A') | (c > 'Z')) {
            evt.consume();
        }
    }//GEN-LAST:event_txtDescripcion_ModificarKeyTyped

    private void txtValorUnitario_ModificarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtValorUnitario_ModificarKeyTyped
        char c = evt.getKeyChar();
        if (c < '0' || c > '9') {
            evt.consume();
        }
    }//GEN-LAST:event_txtValorUnitario_ModificarKeyTyped

    private void btnModificar_ModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificar_ModificarActionPerformed

    }//GEN-LAST:event_btnModificar_ModificarActionPerformed

    private void btnAtras_ModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtras_ModificarActionPerformed

    }//GEN-LAST:event_btnAtras_ModificarActionPerformed

    private void btnListar_Consultar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListar_Consultar1ActionPerformed

    }//GEN-LAST:event_btnListar_Consultar1ActionPerformed

    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed

    }//GEN-LAST:event_btnAtrasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionMobiliario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionMobiliario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionMobiliario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionMobiliario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GestionMobiliario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntGuardar_Registrar;
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnAtras_Modificar;
    private javax.swing.JButton btnAtras_Registra;
    private javax.swing.JButton btnAtras_consultar;
    private javax.swing.JButton btnConsultar_Consultar;
    private javax.swing.JButton btnConsultar_Modificar;
    private javax.swing.JButton btnEliminar_Consultar;
    private javax.swing.JButton btnListar_Consultar1;
    private javax.swing.JButton btnModificar_Modificar;
    private javax.swing.JComboBox<String> comboMobiliario;
    private javax.swing.JPanel consultar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JComboBox<String> jcomboDescripcion;
    private javax.swing.JComboBox<String> jcomboEstado_Modificar;
    private javax.swing.JComboBox<String> jcomboEstado_Registrar;
    private javax.swing.JPanel listar;
    private javax.swing.JPanel modificar;
    private javax.swing.JPanel registrar;
    private javax.swing.JTable tabla_gestionMobilirio;
    public final javax.swing.JTable table_ListadoMobilirio = new javax.swing.JTable();
    private javax.swing.JTextField txtDescripcion_Modificar;
    private javax.swing.JTextField txtIdentificacion_Consultar;
    private javax.swing.JTextField txtIdentificacion_Modificar;
    private javax.swing.JTextField txtIdentificacion_Registrar;
    private javax.swing.JTextField txtValorUnitario_Modificar;
    public final javax.swing.JTextField txtValorUnitario_Registrar = new javax.swing.JTextField();
    // End of variables declaration//GEN-END:variables
}
